# automatically generated by the FlatBuffers compiler, do not modify

# namespace: schema

import flatbuffers
from flatbuffers.compat import import_numpy
from typing import Any
np = import_numpy()

# Upgrade a 3x3 area of rats into a programmer king
class UpgradeToLeadProgrammer(object):
    __slots__ = ['_tab']

    @classmethod
    def SizeOf(cls) -> int:
        return 2

    # UpgradeToLeadProgrammer
    def Init(self, buf: bytes, pos: int):
        self._tab = flatbuffers.table.Table(buf, pos)

    # Placeholder data bc the struct cant be empty
    # UpgradeToLeadProgrammer
    def Phantom(self): return self._tab.Get(flatbuffers.number_types.Uint16Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(0))

def CreateUpgradeToLeadProgrammer(builder, phantom):
    builder.Prep(2, 2)
    builder.PrependUint16(phantom)
    return builder.Offset()
