// automatically generated by the FlatBuffers compiler, do not modify

package battlecode.schema;

@SuppressWarnings("unused")
public final class Action {
  private Action() { }
  public static final byte NONE = 0;
  public static final byte BugFeed = 1;
  public static final byte ProgrammerAttack = 2;
  public static final byte ProgrammerNap = 3;
  public static final byte ProgrammerCollision = 4;
  public static final byte PlaceDirt = 5;
  public static final byte BreakDirt = 6;
  public static final byte CoffeePickup = 7;
  public static final byte CoffeeSpawn = 8;
  public static final byte CoffeeTransfer = 9;
  public static final byte BugScratch = 10;
  public static final byte BugPounce = 11;
  public static final byte PlaceTrap = 12;
  public static final byte RemoveTrap = 13;
  public static final byte TriggerTrap = 14;
  public static final byte ThrowProgrammer = 15;
  public static final byte UpgradeToLeadProgrammer = 16;
  public static final byte ProgrammerPing = 17;
  public static final byte DamageAction = 18;
  public static final byte StunAction = 19;
  public static final byte SpawnAction = 20;
  public static final byte DieAction = 21;
  public static final byte IndicatorStringAction = 22;
  public static final byte IndicatorDotAction = 23;
  public static final byte IndicatorLineAction = 24;

  public static final String[] names = { "NONE", "BugFeed", "ProgrammerAttack", "ProgrammerNap", "ProgrammerCollision", "PlaceDirt", "BreakDirt", "CoffeePickup", "CoffeeSpawn", "CoffeeTransfer", "BugScratch", "BugPounce", "PlaceTrap", "RemoveTrap", "TriggerTrap", "ThrowProgrammer", "UpgradeToLeadProgrammer", "ProgrammerPing", "DamageAction", "StunAction", "SpawnAction", "DieAction", "IndicatorStringAction", "IndicatorDotAction", "IndicatorLineAction", };

  public static String name(int e) { return names[e]; }
}

