// automatically generated by the FlatBuffers compiler, do not modify

package battlecode.schema;

@SuppressWarnings("unused")
public final class RobotType {
  private RobotType() { }
  public static final byte NONE = 0;
  public static final byte PROGRAMMER = 1;
  public static final byte LEAD_PROGRAMMER = 2;
  public static final byte BUG = 3;

  public static final String[] names = { "NONE", "PROGRAMMER", "LEAD_PROGRAMMER", "BUG", };

  public static String name(int e) { return names[e]; }
}

